project:
  type: website
  output-dir: docs
  resources:
  - google77395b81a4e5778b.html

website:
  title: "ImageJ Macro Workshop"
  site-url: "https://marniemaddock.github.io/FIJI-macro-tutorial/"
  description: "Learn how to automate or semi-automate image analysis in ImageJ and FIJI using ImageJ/FIJI macros with this beginner-friendly guide."
  sidebar:
    style: floating

format:
  html:
    toc: true
    toc-depth: 6
    toc-location: left
    theme: cosmo
    css: styles.css
    table-hover: true
    sidebar: true
    metadata:
      google-site-verification: "Yl5oJWY-HTVA-q5QncfpMR0TLVEtV9MNmGy8dbswmIM"
  