project:
  type: website
  output-dir: docs

website:
  title: "ImageJ Macro Workshop"
  sidebar:
    style: floating

format:
  html:
    toc: true
    toc-depth: 6
    toc-location: left
    theme: cosmo
    css: styles.css
    table-hover: true
    sidebar: true
  